import type { Metadata } from 'next'
import { ArrowLeft } from '@phosphor-icons/react/dist/ssr/index'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div>
      <div className="flex items-center h-20 bg-purple-50">
        <button className="flex items-center gap-0.5 font-extralight">
          <ArrowLeft className="opacity-50" size={18} />
          <label className="text-extralight">Back</label>
        </button>
      </div>
      <div>{children}</div>
    </div>
  )
}
